import {
  BotIcon,
  CpuIcon,
  UserIcon,
  EuroIcon,
  UsersIcon,
  BrainIcon,
  CloudIcon,
  BuildingIcon,
  SmartphoneIcon,
} from "lucide-react";
import { City } from "@/types/types";

export const cities: City[] = [
  {
    id: "oradea",
    name: "Oradea",
    country: "Romania",
    position: [47.0722, 21.9211] as [number, number],
    monthlyCosts: {
      rent: 400,
      food: 300,
      utilities: 100,
      coworking: 150,
      transport: 30,
      medical: 80,
    },
    startupFriendliness: 68,
  },
  {
    id: "vienna",
    name: "Vienna",
    country: "Austria",
    position: [48.2082, 16.3738] as [number, number],
    monthlyCosts: {
      rent: 800,
      food: 300,
      utilities: 150,
      coworking: 250,
      transport: 50,
      medical: 100,
    },
    startupFriendliness: 78,
  },
  {
    id: "brussels",
    name: "Brussels",
    country: "Belgium",
    position: [50.8503, 4.3517] as [number, number],
    monthlyCosts: {
      rent: 1000,
      food: 350,
      utilities: 200,
      coworking: 300,
      transport: 60,
      medical: 120,
    },
    startupFriendliness: 76,
  },
  {
    id: "sofia",
    name: "Sofia",
    country: "Bulgaria",
    position: [42.698334, 23.319941] as [number, number],
    monthlyCosts: {
      rent: 400,
      food: 200,
      utilities: 100,
      coworking: 150,
      transport: 30,
      medical: 80,
    },
    startupFriendliness: 70,
  },
  {
    id: "prague",
    name: "Prague",
    country: "Czechia",
    position: [50.073658, 14.41854] as [number, number],
    monthlyCosts: {
      rent: 700,
      food: 250,
      utilities: 120,
      coworking: 200,
      transport: 40,
      medical: 90,
    },
    startupFriendliness: 75,
  },
  {
    id: "copenhagen",
    name: "Copenhagen",
    country: "Denmark",
    position: [55.676098, 12.568337] as [number, number],
    monthlyCosts: {
      rent: 1200,
      food: 400,
      utilities: 250,
      coworking: 350,
      transport: 70,
      medical: 150,
    },
    startupFriendliness: 82,
  },
  {
    id: "tallinn",
    name: "Tallinn",
    country: "Estonia",
    position: [59.437, 24.7536] as [number, number],
    monthlyCosts: {
      rent: 800,
      food: 300,
      utilities: 150,
      coworking: 250,
      transport: 50,
      medical: 100,
    },
    startupFriendliness: 80,
  },
  {
    id: "helsinki",
    name: "Helsinki",
    country: "Finland",
    position: [60.1695, 24.9354] as [number, number],
    monthlyCosts: {
      rent: 1000,
      food: 350,
      utilities: 200,
      coworking: 300,
      transport: 60,
      medical: 120,
    },
    startupFriendliness: 78,
  },
  {
    id: "athens",
    name: "Athens",
    country: "Greece",
    position: [37.98381, 23.727539] as [number, number],
    monthlyCosts: {
      rent: 600,
      food: 250,
      utilities: 150,
      coworking: 200,
      transport: 40,
      medical: 100,
    },
    startupFriendliness: 72,
  },
  {
    id: "budapest",
    name: "Budapest",
    country: "Hungary",
    position: [47.497913, 19.040236] as [number, number],
    monthlyCosts: {
      rent: 500,
      food: 200,
      utilities: 100,
      coworking: 150,
      transport: 30,
      medical: 80,
    },
    startupFriendliness: 74,
  },
  {
    id: "dublin",
    name: "Dublin",
    country: "Ireland",
    position: [53.35014, -6.266155] as [number, number],
    monthlyCosts: {
      rent: 1500,
      food: 400,
      utilities: 250,
      coworking: 400,
      transport: 70,
      medical: 150,
    },
    startupFriendliness: 85,
  },
  {
    id: "rome",
    name: "Rome",
    country: "Italy",
    position: [41.902782, 12.496366] as [number, number],
    monthlyCosts: {
      rent: 1000,
      food: 350,
      utilities: 200,
      coworking: 300,
      transport: 60,
      medical: 120,
    },
    startupFriendliness: 77,
  },

  {
    id: "tartu",
    name: "Tartu",
    country: "Estonia",
    position: [58.3795, 26.7287] as [number, number],
    monthlyCosts: {
      rent: 290,
      food: 450,
      utilities: 130,
      coworking: 180,
      transport: 45,
      medical: 90,
    },
    startupFriendliness: 70,
  },
  {
    id: "innsbruck",
    name: "Innsbruck",
    country: "Austria",
    position: [47.2686, 11.3988] as [number, number],
    monthlyCosts: {
      rent: 320,
      food: 650,
      utilities: 160,
      coworking: 230,
      transport: 55,
      medical: 110,
    },
    startupFriendliness: 70,
  },

  {
    id: "riga",
    name: "Riga",
    country: "Latvia",
    position: [56.946285, 24.105078] as [number, number],
    monthlyCosts: {
      rent: 600,
      food: 250,
      utilities: 150,
      coworking: 200,
      transport: 40,
      medical: 100,
    },
    startupFriendliness: 70,
  },
  {
    id: "vilnius",
    name: "Vilnius",
    country: "Lithuania",
    position: [54.6872, 25.2797] as [number, number],
    monthlyCosts: {
      rent: 600,
      food: 250,
      utilities: 150,
      coworking: 200,
      transport: 40,
      medical: 100,
    },
    startupFriendliness: 72,
  },
  {
    id: "oslo",
    name: "Oslo",
    country: "Norway",
    position: [59.9139, 10.7522] as [number, number],
    monthlyCosts: {
      rent: 1500,
      food: 400,
      utilities: 250,
      coworking: 400,
      transport: 70,
      medical: 150,
    },
    startupFriendliness: 80,
  },

  {
    id: "brno",
    name: "Brno",
    country: "Czech Republic",
    position: [49.1951, 16.6068] as [number, number],
    monthlyCosts: {
      rent: 300,
      food: 600,
      utilities: 150,
      coworking: 200,
      transport: 50,
      medical: 100,
    },
    startupFriendliness: 70,
  },

  {
    id: "nicosia",
    name: "Nicosia",
    country: "Cyprus",
    position: [35.1706, 33.8791] as [number, number],
    monthlyCosts: {
      rent: 350,
      food: 1000,
      utilities: 200,
      coworking: 300,
      transport: 100,
      medical: 100,
    },
    startupFriendliness: 70,
  },

  {
    id: "kaunas",
    name: "Kaunas",
    country: "Lithuania",
    position: [54.9014, 23.9439] as [number, number],
    monthlyCosts: {
      rent: 350,
      food: 500,
      utilities: 150,
      coworking: 200,
      transport: 60,
      medical: 100,
    },
    startupFriendliness: 70,
  },

  {
    id: "zagreb",
    name: "Zagreb",
    country: "Croatia",
    position: [45.815, 15.9819] as [number, number],
    monthlyCosts: {
      rent: 300,
      food: 600,
      utilities: 150,
      coworking: 200,
      transport: 50,
      medical: 100,
    },
    startupFriendliness: 70,
  },

  {
    id: "graz",
    name: "Graz",
    country: "Austria",
    position: [47.0722, 11.3988] as [number, number],
    monthlyCosts: {
      rent: 400,
      food: 800,
      utilities: 200,
      coworking: 250,
      transport: 90,
      medical: 120,
    },
    startupFriendliness: 76,
  },
  {
    id: "warsaw",
    name: "Warsaw",
    country: "Poland",
    position: [52.2297, 21.0122] as [number, number],
    monthlyCosts: {
      rent: 600,
      food: 250,
      utilities: 150,
      coworking: 200,
      transport: 40,
      medical: 100,
    },
    startupFriendliness: 76,
  },
  {
    id: "lisbon",
    name: "Lisbon",
    country: "Portugal",
    position: [38.7169, -9.1399] as [number, number],
    monthlyCosts: {
      rent: 800,
      food: 300,
      utilities: 150,
      coworking: 250,
      transport: 50,
      medical: 100,
    },
    startupFriendliness: 78,
  },
  {
    id: "bratislava",
    name: "Bratislava",
    country: "Slovakia",
    position: [48.1486, 17.1077] as [number, number],
    monthlyCosts: {
      rent: 600,
      food: 250,
      utilities: 150,
      coworking: 200,
      transport: 40,
      medical: 100,
    },
    startupFriendliness: 74,
  },
  {
    id: "ljubljana",
    name: "Ljubljana",
    country: "Slovenia",
    position: [46.0569, 14.5058] as [number, number],
    monthlyCosts: {
      rent: 800,
      food: 300,
      utilities: 150,
      coworking: 250,
      transport: 50,
      medical: 100,
    },
    startupFriendliness: 75,
  },
  {
    id: "stockholm",
    name: "Stockholm",
    country: "Sweden",
    position: [59.3293, 18.0686] as [number, number],
    monthlyCosts: {
      rent: 1500,
      food: 400,
      utilities: 250,
      coworking: 400,
      transport: 70,
      medical: 150,
    },
    startupFriendliness: 83,
  },
  {
    id: "zurich",
    name: "Zurich",
    country: "Switzerland",
    position: [47.3769, 8.5417] as [number, number],
    monthlyCosts: {
      rent: 2000,
      food: 500,
      utilities: 300,
      coworking: 500,
      transport: 80,
      medical: 200,
    },
    startupFriendliness: 85,
  },
  {
    id: "munich",
    name: "Munich",
    country: "Germany",
    position: [48.1351, 11.582] as [number, number],
    monthlyCosts: {
      rent: 1313,
      food: 524,
      utilities: 250,
      coworking: 350,
      transport: 211,
      medical: 150,
    },
    startupFriendliness: 83,
  },
  {
    id: "cluj-napoca",
    name: "Cluj-Napoca",
    country: "Romania",
    position: [46.7712, 23.6236] as [number, number],
    monthlyCosts: {
      rent: 525,
      food: 345,
      utilities: 150,
      coworking: 200,
      transport: 42,
      medical: 100,
    },
    startupFriendliness: 72,
  },
  {
    id: "timisoara",
    name: "Timisoara",
    country: "Romania",
    position: [45.7489, 21.2087] as [number, number],
    monthlyCosts: {
      rent: 370,
      food: 320,
      utilities: 120,
      coworking: 180,
      transport: 40,
      medical: 90,
    },
    startupFriendliness: 70,
  },
  {
    id: "iasi",
    name: "Iasi",
    country: "Romania",
    position: [47.1585, 27.6014] as [number, number],
    monthlyCosts: {
      rent: 400,
      food: 315,
      utilities: 130,
      coworking: 170,
      transport: 40,
      medical: 85,
    },
    startupFriendliness: 69,
  },
  {
    id: "barcelona",
    name: "Barcelona",
    country: "Spain",
    position: [41.3851, 2.1734] as [number, number],
    monthlyCosts: {
      rent: 1100,
      food: 452,
      utilities: 200,
      coworking: 300,
      transport: 152,
      medical: 120,
    },
    startupFriendliness: 80,
  },
  {
    id: "krakow",
    name: "Krakow",
    country: "Poland",
    position: [50.0647, 19.945] as [number, number],
    monthlyCosts: {
      rent: 694,
      food: 336,
      utilities: 150,
      coworking: 200,
      transport: 60,
      medical: 100,
    },
    startupFriendliness: 74,
  },
  {
    id: "milan",
    name: "Milan",
    country: "Italy",
    position: [45.4642, 9.19] as [number, number],
    monthlyCosts: {
      rent: 1250,
      food: 366,
      utilities: 190,
      coworking: 300,
      transport: 39,
      medical: 120,
    },
    startupFriendliness: 78,
  },
  {
    id: "skopje",
    name: "Skopje",
    country: "North Macedonia",
    position: [41.9981, 21.4254] as [number, number],
    monthlyCosts: {
      rent: 400,
      food: 274,
      utilities: 100,
      coworking: 150,
      transport: 52,
      medical: 80,
    },
    startupFriendliness: 66,
  },
  {
    id: "lyon",
    name: "Lyon",
    country: "France",
    position: [45.764, 4.8357] as [number, number],
    monthlyCosts: {
      rent: 777,
      food: 524,
      utilities: 200,
      coworking: 300,
      transport: 130,
      medical: 120,
    },
    startupFriendliness: 77,
  },
];

export const majorHub: City[] = [
  {
    id: "barcelona",
    name: "Barcelona",
    country: "Spain",
    position: [41.3851, 2.1734] as [number, number],
    monthlyCosts: {
      rent: 1100,
      food: 452,
      utilities: 200,
      coworking: 300,
      transport: 152,
      medical: 120,
    },
    startupFriendliness: 80,
  },
  {
    id: "zurich",
    name: "Zurich",
    country: "Switzerland",
    position: [47.3769, 8.5417] as [number, number],
    monthlyCosts: {
      rent: 2000,
      food: 500,
      utilities: 300,
      coworking: 500,
      transport: 80,
      medical: 200,
    },
    startupFriendliness: 85,
  },
  {
    id: "stockholm",
    name: "Stockholm",
    country: "Sweden",
    position: [59.3293, 18.0686] as [number, number],
    monthlyCosts: {
      rent: 1500,
      food: 400,
      utilities: 250,
      coworking: 400,
      transport: 70,
      medical: 150,
    },
    startupFriendliness: 83,
  },
  {
    id: "dublin",
    name: "Dublin",
    country: "Ireland",
    position: [53.35014, -6.266155] as [number, number],
    monthlyCosts: {
      rent: 1500,
      food: 400,
      utilities: 250,
      coworking: 400,
      transport: 70,
      medical: 150,
    },
    startupFriendliness: 85,
  },
  {
    id: "munich",
    name: "Munich",
    country: "Germany",
    position: [48.1351, 11.582] as [number, number],
    monthlyCosts: {
      rent: 1313,
      food: 524,
      utilities: 250,
      coworking: 350,
      transport: 211,
      medical: 150,
    },
    startupFriendliness: 83,
  },
  {
    id: "lyon",
    name: "Lyon",
    country: "France",
    position: [45.764, 4.8357] as [number, number],
    monthlyCosts: {
      rent: 777,
      food: 524,
      utilities: 200,
      coworking: 300,
      transport: 130,
      medical: 120,
    },
    startupFriendliness: 77,
  },
  {
    id: "copenhagen",
    name: "Copenhagen",
    country: "Denmark",
    position: [55.676098, 12.568337] as [number, number],
    monthlyCosts: {
      rent: 1200,
      food: 400,
      utilities: 250,
      coworking: 350,
      transport: 70,
      medical: 150,
    },
    startupFriendliness: 82,
  },
];

export const hiddenGem: City[] = [
  {
    id: "oslo",
    name: "Oslo",
    country: "Norway",
    position: [59.9139, 10.7522] as [number, number],
    monthlyCosts: {
      rent: 1500,
      food: 400,
      utilities: 250,
      coworking: 400,
      transport: 70,
      medical: 150,
    },
    startupFriendliness: 80,
  },
  {
    id: "oradea",
    name: "Oradea",
    country: "Romania",
    position: [47.0722, 21.9211] as [number, number],
    monthlyCosts: {
      rent: 400,
      food: 300,
      utilities: 100,
      coworking: 150,
      transport: 30,
      medical: 80,
    },
    startupFriendliness: 68,
  },
  {
    id: "brno",
    name: "Brno",
    country: "Czech Republic",
    position: [49.1951, 16.6068] as [number, number],
    monthlyCosts: {
      rent: 300,
      food: 600,
      utilities: 150,
      coworking: 200,
      transport: 50,
      medical: 100,
    },
    startupFriendliness: 70,
  },
  {
    id: "skopje",
    name: "Skopje",
    country: "North Macedonia",
    position: [41.9981, 21.4254] as [number, number],
    monthlyCosts: {
      rent: 400,
      food: 274,
      utilities: 100,
      coworking: 150,
      transport: 52,
      medical: 80,
    },
    startupFriendliness: 66,
  },
  {
    id: "graz",
    name: "Graz",
    country: "Austria",
    position: [47.0722, 11.3988] as [number, number],
    monthlyCosts: {
      rent: 400,
      food: 800,
      utilities: 200,
      coworking: 250,
      transport: 90,
      medical: 120,
    },
    startupFriendliness: 76,
  },
  {
    id: "zagreb",
    name: "Zagreb",
    country: "Croatia",
    position: [45.815, 15.9819] as [number, number],
    monthlyCosts: {
      rent: 300,
      food: 600,
      utilities: 150,
      coworking: 200,
      transport: 50,
      medical: 100,
    },
    startupFriendliness: 70,
  },
  {
    id: "nicosia",
    name: "Nicosia",
    country: "Cyprus",
    position: [35.1706, 33.8791] as [number, number],
    monthlyCosts: {
      rent: 350,
      food: 1000,
      utilities: 200,
      coworking: 300,
      transport: 100,
      medical: 100,
    },
    startupFriendliness: 70,
  },
  {
    id: "kaunas",
    name: "Kaunas",
    country: "Lithuania",
    position: [54.9014, 23.9439] as [number, number],
    monthlyCosts: {
      rent: 350,
      food: 500,
      utilities: 150,
      coworking: 200,
      transport: 60,
      medical: 100,
    },
    startupFriendliness: 70,
  },
];

export const emergingHub: City[] = [
  {
    id: "milan",
    name: "Milan",
    country: "Italy",
    position: [45.4642, 9.19] as [number, number],
    monthlyCosts: {
      rent: 1250,
      food: 366,
      utilities: 190,
      coworking: 300,
      transport: 39,
      medical: 120,
    },
    startupFriendliness: 78,
  },
  {
    id: "ljubljana",
    name: "Ljubljana",
    country: "Slovenia",
    position: [46.0569, 14.5058] as [number, number],
    monthlyCosts: {
      rent: 800,
      food: 300,
      utilities: 150,
      coworking: 250,
      transport: 50,
      medical: 100,
    },
    startupFriendliness: 75,
  },
  {
    id: "bratislava",
    name: "Bratislava",
    country: "Slovakia",
    position: [48.1486, 17.1077] as [number, number],
    monthlyCosts: {
      rent: 600,
      food: 250,
      utilities: 150,
      coworking: 200,
      transport: 40,
      medical: 100,
    },
    startupFriendliness: 74,
  },
  {
    id: "lisbon",
    name: "Lisbon",
    country: "Portugal",
    position: [38.7169, -9.1399] as [number, number],
    monthlyCosts: {
      rent: 800,
      food: 300,
      utilities: 150,
      coworking: 250,
      transport: 50,
      medical: 100,
    },
    startupFriendliness: 78,
  },
  {
    id: "krakow",
    name: "Krakow",
    country: "Poland",
    position: [50.0647, 19.945] as [number, number],
    monthlyCosts: {
      rent: 694,
      food: 336,
      utilities: 150,
      coworking: 200,
      transport: 60,
      medical: 100,
    },
    startupFriendliness: 74,
  },
  {
    id: "warsaw",
    name: "Warsaw",
    country: "Poland",
    position: [52.2297, 21.0122] as [number, number],
    monthlyCosts: {
      rent: 600,
      food: 250,
      utilities: 150,
      coworking: 200,
      transport: 40,
      medical: 100,
    },
    startupFriendliness: 76,
  },
  {
    id: "riga",
    name: "Riga",
    country: "Latvia",
    position: [56.946285, 24.105078] as [number, number],
    monthlyCosts: {
      rent: 600,
      food: 250,
      utilities: 150,
      coworking: 200,
      transport: 40,
      medical: 100,
    },
    startupFriendliness: 70,
  },
  {
    id: "budapest",
    name: "Budapest",
    country: "Hungary",
    position: [47.497913, 19.040236] as [number, number],
    monthlyCosts: {
      rent: 500,
      food: 200,
      utilities: 100,
      coworking: 150,
      transport: 30,
      medical: 80,
    },
    startupFriendliness: 74,
  },
  {
    id: "athens",
    name: "Athens",
    country: "Greece",
    position: [37.98381, 23.727539] as [number, number],
    monthlyCosts: {
      rent: 600,
      food: 250,
      utilities: 150,
      coworking: 200,
      transport: 40,
      medical: 100,
    },
    startupFriendliness: 72,
  },
  {
    id: "helsinki",
    name: "Helsinki",
    country: "Finland",
    position: [60.1695, 24.9354] as [number, number],
    monthlyCosts: {
      rent: 1000,
      food: 350,
      utilities: 200,
      coworking: 300,
      transport: 60,
      medical: 120,
    },
    startupFriendliness: 78,
  },
  {
    id: "vienna",
    name: "Vienna",
    country: "Austria",
    position: [48.2082, 16.3738] as [number, number],
    monthlyCosts: {
      rent: 800,
      food: 300,
      utilities: 150,
      coworking: 250,
      transport: 50,
      medical: 100,
    },
    startupFriendliness: 78,
  },
  {
    id: "brussels",
    name: "Brussels",
    country: "Belgium",
    position: [50.8503, 4.3517] as [number, number],
    monthlyCosts: {
      rent: 1000,
      food: 350,
      utilities: 200,
      coworking: 300,
      transport: 60,
      medical: 120,
    },
    startupFriendliness: 76,
  },
  {
    id: "sofia",
    name: "Sofia",
    country: "Bulgaria",
    position: [42.698334, 23.319941] as [number, number],
    monthlyCosts: {
      rent: 400,
      food: 200,
      utilities: 100,
      coworking: 150,
      transport: 30,
      medical: 80,
    },
    startupFriendliness: 70,
  },
  {
    id: "prague",
    name: "Prague",
    country: "Czechia",
    position: [50.073658, 14.41854] as [number, number],
    monthlyCosts: {
      rent: 700,
      food: 250,
      utilities: 120,
      coworking: 200,
      transport: 40,
      medical: 90,
    },
    startupFriendliness: 75,
  },
];

// Founder personas
export const founderPersonas = [
  {
    id: "established",
    name: "Already Established Startup",
    description: "Growing company looking to expand efficiently",
    icon: <BuildingIcon className="h-5 w-5" />,
    defaults: {
      teamSize: 3,
      burnRate: 5000,
      additionalExpenses: 2000,
      isRemoteTeam: false,
      timeframe: 6,
    },
  },
  {
    id: "ambitious",
    name: "The Ambitious Team",
    description: "2-3 people, higher burn, faster growth",
    icon: <UsersIcon className="h-5 w-5" />,
    defaults: {
      teamSize: 3,
      burnRate: 5000,
      additionalExpenses: 1600,
      isRemoteTeam: false,
      timeframe: 6,
    },
  },
  {
    id: "solo",
    name: "Solo Founder",
    description: "Building alone, focused on efficiency",
    icon: <UserIcon className="h-5 w-5" />,
    defaults: {
      teamSize: 1,
      burnRate: 2000,
      additionalExpenses: 800,
      isRemoteTeam: true,
      timeframe: 12,
    },
  },
];

// Startup types
export const startupTypes = [
  {
    id: "saas",
    name: "SaaS",
    description: "Software as a Service",
    icon: <CloudIcon className="h-5 w-5" />,
  },
  {
    id: "robotics",
    name: "Robotics",
    description: "Automated systems and robotics",
    icon: <BotIcon className="h-5 w-5" />,
  },
  {
    id: "fintech",
    name: "Fintech",
    description: "Financial technology",
    icon: <EuroIcon className="h-5 w-5" />,
  },
  {
    id: "hardware",
    name: "Hardware",
    description: "Physical technology products",
    icon: <CpuIcon className="h-5 w-5" />,
  },
  {
    id: "ai",
    name: "AI/ML",
    description: "Artificial Intelligence and ML",
    icon: <BrainIcon className="h-5 w-5" />,
  },
  {
    id: "mobile",
    name: "Mobile App",
    description: "Mobile applications",
    icon: <SmartphoneIcon className="h-5 w-5" />,
  },
];

// City profile preferences
export const cityProfiles = [
  {
    id: "major",
    name: "Major Hub",
    description: "Large cities with established startup ecosystems",
    icon: <UsersIcon className="h-5 w-5" />,
    cities: ["london", "paris", "berlin", "amsterdam"],
    pros: [
      "Access to investors",
      "Large talent pool",
      "Networking opportunities",
    ],
    cons: ["Higher costs", "More competition", "Faster pace"],
  },
  {
    id: "emerging",
    name: "Emerging Hub",
    description: "Growing cities with developing startup scenes",
    icon: <UserIcon className="h-5 w-5" />,
    cities: ["madrid", "barcelona"],
    pros: [
      "Lower costs than major hubs",
      "Growing ecosystem",
      "Government incentives",
    ],
    cons: [
      "Smaller investor network",
      "Limited talent pool",
      "Fewer resources",
    ],
  },
  {
    id: "hidden-gem",
    name: "Hidden Gem",
    description: "Smaller cities with unique advantages",
    icon: <EuroIcon className="h-5 w-5" />,
    cities: ["madrid", "barcelona"],
    pros: ["Much lower costs", "Less competition", "Better work-life balance"],
    cons: ["Limited access to capital", "Smaller networks", "Fewer resources"],
  },
];

// Bright Labs benefits
export const brightLabsBenefits = {
  housing: true,
  food: true,
  coworking: true,
  stipend: 2000,
  mentorship: true,
  networking: true,
};
